.nh
.TH "run-flogo-app" "3" "Aug 2022" "" ""

.SH NAME
.PP
run-flogo-app - Run the most recent flogo app from your apps dir


.SH SYNOPSIS
.PP
\fBrun-flogo-app [flags]\fP


.SH DESCRIPTION
.PP
Run the most recent flogo app from your configured apps dir. If the apps dir is not configured, the default will be used


.SH OPTIONS
.PP
\fB-d\fP, \fB--debug\fP[=false]
	Enable debug logs

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for run-flogo-app

.PP
\fB-l\fP, \fB--list\fP[=false]
	List last 5 apps and choose a number to run

.PP
\fB-n\fP, \fB--name\fP=""
	Run app with given (partial) name


.SH SEE ALSO
.PP
\fBrun-flogo-app-config(3)\fP, \fBrun-flogo-app-delete(3)\fP, \fBrun-flogo-app-install(3)\fP, \fBrun-flogo-app-uninstall(3)\fP, \fBrun-flogo-app-version(3)\fP
