.nh
.TH "run-flogo-app" "3" "Aug 2022" "" ""

.SH NAME
.PP
run-flogo-app-config - Print current config file


.SH SYNOPSIS
.PP
\fBrun-flogo-app config [flags]\fP


.SH DESCRIPTION
.PP
Print current config file


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for config


.SH SEE ALSO
.PP
\fBrun-flogo-app(3)\fP
