.nh
.TH "run-flogo-app" "3" "Oct 2022" "" ""

.SH NAME
.PP
run-flogo-app-install - Install the program


.SH SYNOPSIS
.PP
\fBrun-flogo-app install [flags]\fP


.SH DESCRIPTION
.PP
Install the program


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install


.SH SEE ALSO
.PP
\fBrun-flogo-app(3)\fP
