.nh
.TH "run-flogo-app" "3" "Oct 2022" "" ""

.SH NAME
.PP
run-flogo-app-update - Update the app with latest version


.SH SYNOPSIS
.PP
\fBrun-flogo-app update [flags]\fP


.SH DESCRIPTION
.PP
Update the app with latest version


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update


.SH SEE ALSO
.PP
\fBrun-flogo-app(3)\fP
