.nh
.TH "run-flogo-app" "3" "Aug 2022" "" ""

.SH NAME
.PP
run-flogo-app-version - Print the version info of the program


.SH SYNOPSIS
.PP
\fBrun-flogo-app version [flags]\fP


.SH DESCRIPTION
.PP
Print the version info of the program


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH SEE ALSO
.PP
\fBrun-flogo-app(3)\fP
