.nh
.TH "run-flogo-app" "3" "Oct 2022" "" ""

.SH NAME
.PP
run-flogo-app-delete - Delete all the flogo apps in apps dir


.SH SYNOPSIS
.PP
\fBrun-flogo-app delete [flags]\fP


.SH DESCRIPTION
.PP
Delete all the flogo apps in apps dir


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH SEE ALSO
.PP
\fBrun-flogo-app(3)\fP
