.nh
.TH "run-flogo-app" "3" "Aug 2022" "" ""

.SH NAME
.PP
run-flogo-app-uninstall - Uninstall the program


.SH SYNOPSIS
.PP
\fBrun-flogo-app uninstall [flags]\fP


.SH DESCRIPTION
.PP
Uninstall the program


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for uninstall


.SH SEE ALSO
.PP
\fBrun-flogo-app(3)\fP
